image: "rust:latest"

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
#before_script:
#- apt-get update -yqq
#- apt-get install -yqq --no-install-recommends build-essential

.code_change_: &code_change
  only:
    changes:
    - crates
    - Cargo.toml

stages:
  - test
  - doc
  - deploy

test:cargo:
  <<: *code_change
  stage: test
  script:
  - rustc --version && cargo --version
  - cargo test --all --verbose

test:kcov:
  <<: *code_change
  stage: test
  image: docker:latest
  services: 
  - docker:dind
  script:
  - docker --version
  - ./scripts/kcov.sh
  artifacts:
    paths:
    - cov/
    expire_in: 1 hour

pages:
  <<: *code_change
  stage: doc
  script:
  - cargo doc --all
  - mkdir -p public
  - cp -R target/doc/* public/
  artifacts:
    paths:
    - public
  only:
    refs:
    - master

deploy:codecov:
  <<: *code_change
  stage: deploy
  script:
  - ls
  - curl -v -s https://codecov.io/bash | bash

crates.io:
  <<: *code_change
  image: registry.gitlab.com/torkleyy/cargo-publish-all:latest
  stage: deploy
  script:
  - cargo-publish-all --token $CRATES_IO_TOKEN --yes
  only:
    refs:
    - master
