image: "rust:latest"

.code_change:
  only:
    changes:
    - crates/**
    - Cargo.toml

.master_code_change:
  only:
    changes:
    - crates/**
    - Cargo.toml
    refs:
    - master

stages:
  - test
  - doc
  - deploy

test:cargo:
  extends: .code_change
  stage: test
  script:
  - rustc --version && cargo --version
  - cargo test --all --verbose

test:kcov:
  extends: .code_change
  stage: test
  image: docker:latest
  services: 
  - docker:dind
  script:
  - docker --version
  - ./scripts/kcov.sh
  artifacts:
    paths:
    - cov/
    expire_in: 1 hour

pages:
  extends: .master_code_change
  stage: doc
  script:
  - cargo doc --all
  - mkdir -p public
  - cp -R target/doc/* public/
  artifacts:
    paths:
    - public

deploy:codecov:
  extends: .code_change
  stage: deploy
  script:
  - ls
  - curl -v -s https://codecov.io/bash | bash

crates.io:
  extends: .master_code_change
  image: registry.gitlab.com/torkleyy/cargo-publish-all:latest
  stage: deploy
  script:
  - cargo-publish-all --token $CRATES_IO_TOKEN --yes
