codecov:
  notify:
    require_ci_to_pass: yes
  token: 424f63db-0d5a-414b-8711-bd8cd4e2673b

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
